language: python
python:
  - '3.5'
branches:
  only:
   - source
install:
  - pip install pipenv
  - pipenv install --system
  - pelican-themes -i elegant
script:
  - make publish
deploy:
  provider: pages
  repo: aogier/aogier.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: source
